name: hooks_reduct
description: A flutter hooks for reduct library.
version: 1.0.0
repository: https://github.com/Eronildo/hooks_reduct

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  reduct: ^1.0.0
  flutter_hooks: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
