name: hooks_reduct
description: A flutter hooks for reduct library, an elementary yet adaptable state management solution for Dart.
version: 1.0.1
repository: https://github.com/Eronildo/hooks_reduct

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduct: ^1.0.1
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
